"""add cascade mode to tables

Revision ID: f68fb17b1214
Revises: 175e5919d58e
Create Date: 2026-02-12 21:28:04.112399

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f68fb17b1214"
down_revision: Union[str, Sequence[str], None] = "175e5919d58e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("posts_user_id_fkey"), "posts", type_="foreignkey")
    op.create_foreign_key(
        "posts_user_id_fkey", "posts", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("profiles_user_id_fkey"), "profiles", type_="foreignkey")
    op.create_foreign_key(
        "profiles_user_id_fkey",
        "profiles",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("profiles_user_id_fkey", "profiles", type_="foreignkey")
    op.create_foreign_key(
        op.f("profiles_user_id_fkey"), "profiles", "users", ["user_id"], ["id"]
    )
    op.drop_constraint("posts_user_id_fkey", "posts", type_="foreignkey")
    op.create_foreign_key(
        op.f("posts_user_id_fkey"), "posts", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
